name: Publish Python ğŸ distribution ğŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  publish-to-pypi:
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI
    #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nnetsauce  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:   
    - name: Publish distribution ğŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: 'https://github.com/Techtonique/nnetsauce/blob/master/dist/nnetsauce-0.16.2.tar.gz'
        password: ${{ secrets.PYPI_GLOBAL }}
        repository-url: https://test.pypi.org/legacy/
        verbose: true
