name: Publish Python ğŸ distribution ğŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  publish-to-pypi:
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI
    #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nnetsauce  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Debug directory structure
        run: |
          pwd          
          ls -la          
      - name: Find directory two levels higher
        id: find-dir
        run: |
          found_dir=$(find "dist" -maxdepth 2)
          echo "Found directory: $found_dir"
          echo "PACKAGES_DIR=$found_dir" >> $GITHUB_ENV

      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ env.PACKAGES_DIR }}/  # Change to match .tar.gz files
          password: ${{ secrets.PYPI_GLOBAL }}
          repository-url: https://test.pypi.org/legacy/
